name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "rajashekaryakkanti"
        password: "Viaan@1234"

    - name: Build Docker image
      run: docker build -t rajashekaryakkanti/nginx:latest . 
      with:
        context: .
        file: ./Dockerfile

    - name: Push Docker image to Docker Hub
      run: docker push rajashekaryakkanti/nginx:latest
